Markup the bulletin with schema.org properties
cosola-salvia/macile-newsletter pull request #94
Opened 2020-04-24 16:16 UTC by Morban15

2020-04-27 14:00 UTC, misscs reviewed
Una pregunta.

2020-04-27 14:00 UTC, misscs commented on bulletin/index.html
> +	<div class="bupage" itemscope itemtype="http://schema.org/CreativeWork">
Why is CreativeWork the most approapriate scheme for the bulletin? I'm not saying it is wrong, I am curious as to why you felt it was the best option.

2020-04-27 18:22 UTC, misscs commented on bulletin/index.html
> +	<div class="bupage" itemscope itemtype="http://schema.org/CreativeWork">
We talked about it. ++ in agreement with your thinking. Thanks!

2020-04-27 18:40 UTC, misscs requested changes

2020-04-27 18:40 UTC, misscs commented on bulletin/index.html
> +			<article class="buarticle buarticle-main" itemscope itemtype="http://schema.org/CreativeWork">
I think here we could leverage `itemprop="about"`.

2020-04-27 18:40 UTC, misscs commented on bulletin/index.html
>  				<p class="buarticle-hero--large">We are the adventurers; the true founders. High school students from Itabo y San Gregorio de Nigua selected for the <strong>FIRST</strong> MACILE Summer Academy,
Here we can leverage `itemprop="abstract"`

2020-04-27 18:40 UTC, misscs commented on bulletin/index.html
>  			<article class="buarticle" itemscope itemtype="http://schema.org/CreativeWork">
We can remove the `itemscope`. As discussed, `itemprop="text"` suffices.

2020-04-27 19:21 UTC, Morban15 commented
I think we don't have to remove the *CreativeWork* from the `head`

![creative-work-in-head](https://user-images.githubusercontent.com/29107510/80411796-c6362600-889a-11ea-8429-61ae6d203157.png)

![creative-work-in-the-head](https://user-images.githubusercontent.com/29107510/80411797-c6362600-889a-11ea-9898-a73421aaf66f.png)

2020-04-27 19:51 UTC, misscs commented
I think you are right. If we don’t remove it from the head, then do we need to define it in the body again?

2020-04-28 05:20 UTC, Morban15 commented
Yes, we have to add it in both.

2020-04-28 12:58 UTC, misscs commented
> Yes, we have to add it in both.

Makes sense! Each section—`<head>`, `<body>`—are treated as individual entities

2020-04-28 13:04 UTC, misscs approved these changes
:shipit: 

Keep up the great single purpose commits!

2020-04-28 17:15 UTC, merged